#!/usr/bin/env python3
"""Generate the decisions index from one-file-per-decision (KIT-016).

Decisions are files: <decisions_dir>/Dn-<slug>.md, first line `## Dn — title (date)`,
then the four parts. Several agents in several worktrees can each add a file without
touching a shared one. This writes the INDEX — one line per decision, newest last,
SUPERSEDED marks carried through — so a human or an agent gets the quick lookup.

The index is ALWAYS docs/DECISIONS_INDEX.md (open-teleporter's layout). A hand-written
docs/DECISIONS.md, if the repo has one, is a FROZEN legacy log: never touched, its entries
included, numbering continues after it. Never generating docs/DECISIONS.md means a repo
that later merges a branch carrying its own hand-written log gets no add/add conflict.
`decisions_index` in docs/doc-kit.config overrides the location.

    python3 scripts/decisions-index.py            # from pre-commit; prints the path
    python3 scripts/decisions-index.py --check    # exit 1 if the index is stale
"""
import sys; sys.dont_write_bytecode = True  # no __pycache__ litter in adopting repos (KIT-011)
import re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from doc_kit import load_config  # noqa: E402

MARKER = "<!-- generated by ticketing-template from the decision files — do not edit; add a file -->"
HEAD = re.compile(r"^#{1,3}\s+(D\d+)\s*[—-]\s*(.+?)\s*$", re.M)
SUPERSEDED = re.compile(r"SUPERSEDED by (D\d+)")


def entries(root: Path, cfg: dict):
    """(n, id, title, source, superseded_by) for every decision, files and frozen log."""
    out = []
    ddir = root / cfg["decisions_dir"]
    for f in sorted(ddir.glob("D*.md")) if ddir.is_dir() else []:
        text = f.read_text(encoding="utf-8", errors="replace")
        m = HEAD.search(text)
        if not m:
            continue
        sup = SUPERSEDED.search(text)
        out.append((int(m.group(1)[1:]), m.group(1), m.group(2), f.relative_to(root).as_posix(),
                    sup.group(1) if sup else ""))
    frozen = frozen_log(root, cfg)
    if frozen:
        text = frozen.read_text(encoding="utf-8", errors="replace")
        heads = list(HEAD.finditer(text))
        for i, m in enumerate(heads):
            body = text[m.end(): heads[i + 1].start() if i + 1 < len(heads) else len(text)]
            sup = SUPERSEDED.search(body)
            out.append((int(m.group(1)[1:]), m.group(1), m.group(2), frozen.relative_to(root).as_posix(),
                        sup.group(1) if sup else ""))
    out.sort(key=lambda e: e[0])
    return out


def frozen_log(root: Path, cfg: dict):
    """A hand-written docs/DECISIONS.md (no marker) is a frozen legacy log."""
    if cfg.get("decisions_frozen", "").strip():
        p = root / cfg["decisions_frozen"].strip()
        return p if p.is_file() else None
    p = root / "docs" / "DECISIONS.md"
    return p if p.is_file() else None


def index_path(root: Path, cfg: dict) -> Path:
    if cfg.get("decisions_index", "").strip():
        return root / cfg["decisions_index"].strip()
    return root / "docs" / "DECISIONS_INDEX.md"


def render(root: Path, cfg: dict) -> str:
    es = entries(root, cfg)
    fr = frozen_log(root, cfg)
    lines = [MARKER, "# Decisions", "",
             "Append-only, numbered, one FILE each in `" + cfg["decisions_dir"] + "/` (`Dn-<slug>.md`):",
             "what we picked · the alternatives and why each lost · the constraint · what would make",
             "us revisit. To reverse one, add a new file marking the old **SUPERSEDED by Dn**.",
             "New decision: `python3 scripts/wi.py decision new \"<title>\"` — same commit as the change.", ""]
    if fr:
        lines += [f"Entries before the split live in the frozen log `{fr.relative_to(root).as_posix()}` (never edited).", ""]
    if not es:
        lines += ["_No decisions yet._", ""]
    for n, did, title, src, sup in es:
        mark = f" — **SUPERSEDED by {sup}**" if sup else ""
        lines.append(f"- **{did}** — {title}{mark} — [{src}]({'../' + src if src.startswith('docs/') else src})")
    return "\n".join(lines) + "\n"


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    cfg = load_config(root)
    if cfg.get("decisions_index", "").strip().lower() == "none":
        print("decisions index: disabled (decisions_index = none) — this repo keeps its own")
        return 0
    path = index_path(root, cfg)
    text = render(root, cfg)
    if "--check" in sys.argv:
        cur = path.read_text(encoding="utf-8") if path.exists() else ""
        if cur != text:
            print(f"decisions index is stale: {path.relative_to(root)} — run scripts/decisions-index.py", file=sys.stderr)
            return 1
        print(f"decisions index current: {path.relative_to(root)}")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    print(f"{path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
